---
title: "Exercise 6: Tilt illusion analysis"
author: "Your name"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: show
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r warning=FALSE}
library(tidyverse)
library(ggplot2)
```

# Part 1

Loading data
```{r warning=FALSE}
getwd() # make sure you're int the directory you think you are

#load your data in this chunk into a variable dat 

```
# Part 2

Adding helper columns
```{r warning=FALSE}
dat %>% mutate()
```

# Part 3

Some descriptive stats

```{r warning=FALSE}


```

```{r warning=FALSE}


```

```{r warning=FALSE}


```

```{r warning=FALSE}


```

# Part 4

Practice with pivoting

```{r warning=FALSE}



```

# Part 5

## Graphs


This graph shows....
```{r warning=FALSE}



```

This graph shows....

```{r warning=FALSE}



```

This graph shows....
```{r warning=FALSE}



```






